name: Deploy Application

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: npm i  

      - name: Replace secret in config file
        run: |
          sed -i 's/REPLACE_MEANING_OF_LIFE/${{ secrets.MEANING_OF_LIFE }}/g' deploy.js

      - name: Run test script
        run: npm run deploy